spring:
  application:
    name: "eurekaserver"
  config:
    import: "optional:configserver:http://localhost:8000/"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
  info:
    env:
      enabled: true
    metrics:
      logs:
        application: ${spring.application.name}

