global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'configserver'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['configserver:8000']
  - job_name: 'eurekaserver'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'eurekaserver:8070' ]
  - job_name: 'userservice'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'userservice:8083' ]
  - job_name: 'tweetservice'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'chirpservice:8082' ]