spring:
  application:
    name: "Userservice"
  config:
    import: "optional:configserver:http://localhost:8000/"
  data:
    mongodb:
      host: "localhost"
      password: ""
      database: "Twitter"
      port: 27017

management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"





info:
  app:
    name: "Twitter user service"
    description: "Twitter user service"
    version: "1.0.0"