spring:
  application:
    name: "userservice"
  config:
    import: "optional:configserver:http://localhost:8000/"
  data:
    mongodb:
      host: "localhost"
      password: ""
      database: "Twitter"
      port: 27017

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
  metrics:
    tags:
      application: ${spring.application.name}


info:
  app:
    name: "Twitter user service"
    description: "Twitter user service"
    version: "1.0.0"
  metrics:
    logs:
      application: ${spring.application.name}