
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8070/eureka/

spring:
  application:
    name: twitter-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: "http://localhost:7080/realms/twitter-clone/protocol/openid-connect/certs"


keycloak:
  auth-server-url: http://localhost:7080/auth
  realm: twitter-clone
  resource: authenticationClientId
  public-client: true
  principal-attribute: preferred_username

server:
  port: 8084

management:
  info:
    env:
      enabled: true
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"


info:
  app:
    name: "Twitter Gateway service"
    description: "Twitter Gateway service"
    version: "1.0.0"
  metrics:
    logs:
      application: ${spring.application.name}